[project]
name = "strengther"
version = "0.1.0"
description = ""
authors = [{ name = "Brian Cusack", email = "bcusack@gmail.com" }]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pybit",
 "pydantic",
 "colorama",
 "pandas",
 "fastapi",
 "uvicorn",
 "apscheduler>=3.11.0",
]

[project.scripts]
strengther = "strengther.app:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["pytest"]
